apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: homelab
  namespace: flux-system
spec:
  interval: 10m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./"
  prune: true
  wait: true
  dependsOn:
    - name: flux-system

  resources:
    - ./csi-driver-nfs
    - ./ingress-nginx
    - ./metallb
