apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: csi-driver-nfs-overlay
  namespace: flux-system

resources:
  - ../../base/csi-driver-nfs
  - storageclass.yaml

patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: csi-driver-nfs
        namespace: kube-system
      spec:
        values:
          nfs:
            server: 192.168.1.121
            share: /volume1/k3sdata
