apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: ingress-nginx-overlay
  namespace: flux-system

resources:
  - ../../base/ingress-nginx

patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: ingress-nginx
        namespace: ingress-nginx
      spec:
        values:
          controller:
            service:
              annotations:
                metallb.universe.tf/address-pool: homelab-addresspool
    target:
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress-nginx
