apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
  - ../../base
  - storageclass.yaml
configMapGenerator:
  - name: csi-driver-nfs-overlay-values
    files:
      - values.yaml