apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helmrelease.yaml
  - helmrepository.yaml
configMapGenerator:
  - name: metallb-base-values
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml