apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: metallb-system
resources:
  - ../../base
  - addresspool.yaml
configMapGenerator:
  - name: metallb-overlay-values
    files:
      - values.yaml