apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrepository.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: csi-driver-nfs-base-values
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml