# apps/networking/metallb/addresspool.yaml

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-addresspool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.1.80-192.168.1.99

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelab-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - home-addresspool
