apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization

resources:
  - ../../../base/ingress-nginx

patches:
  - patch: patches/helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress-nginx
