apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/ingress-nginx

patches:
  - patch: patches/helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: ingress-nginx
      namespace: ingress-nginx
